"""
Genre calibration test corpus.
10 texts per genre: narrative, expository, essay.
"""

corpus = {
    "narrative": [
        "The old man walked along the beach at sunset. He paused to watch the waves crash against the shore. A seagull circled overhead calling out to the sky. The man smiled remembering his youth by the sea. Those days seemed so far away now in the present. He turned slowly and headed back toward his small cottage. The path was lined with wild flowers and tall grass.",
        "Sarah opened the envelope with trembling fingers. She had been waiting for this letter for three long months. The words on the page blurred before her tear-filled eyes. Her dream had finally come true after years of effort. She had been accepted into the prestigious music program. Sarah immediately called her mother to share the wonderful news.",
        "The detective examined the crime scene with careful precision. Something about the broken window did not make sense to him. The glass shards were scattered on the inside of the room. The victim had no known enemies according to neighbors. But the detective sensed that someone was not telling the truth. He decided to question the witnesses one more time.",
        "Emma walked into the garden as the morning sun rose slowly. The roses climbed the ancient stone walls with delicate beauty. She tended these flowers every single day without fail. The ritual brought her a peace she could find nowhere else. Nature had become her truest and most reliable companion. Emma smiled as butterflies danced among the lavender bushes.",
        "The storm raged through the dark night without showing any mercy. Thunder shook the old farmhouse to its very foundations. Lightning illuminated the frightened faces of the family inside. They huddled together in the kitchen waiting for dawn to arrive. Morning brought a strange calm but also revealed the destruction outside. The barn was completely gone swept away by the violent winds.",
        "Jack climbed the mountain with nothing but determination and hope. The trail grew steeper with each passing hour of the day. His legs burned but he refused to stop or look back down. He had promised his father he would reach the summit alone. The view from the top made every painful step worth the effort. Jack stood there in silence watching the sun paint the valley below.",
        "Maria unpacked her belongings in the small university dormitory room. She had never been this far away from her family before today. The city outside her window seemed enormous and overwhelming right now. But she felt a spark of excitement mixed with her nervousness. This was the beginning of a new chapter in her young life. Maria took a deep breath and started decorating her side of the room.",
        "The train pulled into the station exactly at midnight under the rain. He stepped onto the platform with nothing but a small leather suitcase. The city looked different from how he remembered it twenty years ago. Everything had changed except the old clock tower still standing tall. He wondered if anyone would recognize him after all these years away. The station was nearly empty at this late hour of the night.",
        "Lily found the old photograph tucked inside her grandmothers dusty diary. The image showed a young woman with familiar eyes and a gentle smile. She realized with a start that it was her grandmother at age twenty. The photograph was taken in front of a bakery that no longer existed. Lily felt a strange connection to this young woman she had never truly known. She carefully placed the photograph back between the yellowed pages.",
        "The fisherman cast his net into the dark water before the sunrise. He had been doing this same routine for over forty years now. The sea had given him everything and taken much away as well. His son had moved to the city and never learned the old ways. But the fisherman did not feel bitter about the changing of the times. The sun rose over the horizon painting the water in shades of gold.",
    ],
    "expository": [
        "The Industrial Revolution fundamentally transformed European society in the eighteenth century. It introduced mechanized production methods that replaced traditional manual labor. These new machines dramatically increased manufacturing output and overall economic efficiency. They also created entirely new social classes including the industrial working class. Factory owners accumulated enormous wealth during this period of rapid change. However workers faced harsh conditions with extremely long hours and very low wages. Child labor became widespread in textile mills and dangerous coal mines. These problems eventually led to labor reforms and the rise of union movements.",
        "Photosynthesis is the process by which plants convert sunlight into chemical energy. The reaction takes place in chloroplasts using chlorophyll as a catalyst. Carbon dioxide enters the leaves through tiny pores called stomata on the surface. Water is absorbed by the roots and transported upward through the xylem vessels. Sunlight provides the energy needed to split water molecules into hydrogen and oxygen. The plant releases oxygen as a waste product into the surrounding atmosphere. Glucose is produced as the primary energy source for the entire plant.",
        "The American Civil War began in 1861 after decades of sectional tension over slavery. Eleven southern states seceded from the Union to form their own Confederate government. President Abraham Lincoln declared the secession illegal and took military action to preserve the Union. The war lasted four years and resulted in over 600000 American casualties on both sides. The Union victory in 1865 led to the abolition of slavery throughout the entire country. However the period of Reconstruction that followed proved to be deeply controversial and difficult.",
        "Climate change refers to long-term shifts in global temperatures and weather patterns. Human activities since the Industrial Revolution have been the primary driver of this phenomenon. The burning of fossil fuels releases greenhouse gases like carbon dioxide and methane into the atmosphere. These gases trap heat from the sun causing the planet to warm gradually over time. Scientists have documented rising sea levels melting ice caps and more frequent extreme weather events. International agreements like the Paris Accord aim to limit global temperature increases to 1.5 degrees Celsius.",
        "The theory of evolution by natural selection was proposed by Charles Darwin in 1859. It explains how species change over time through the differential survival of organisms. Individuals with traits better suited to their environment are more likely to survive and reproduce. These advantageous traits become more common in the population over many successive generations. The process can eventually lead to the formation of entirely new species over geological time scales. Evidence from fossils genetics and comparative anatomy strongly supports this theory.",
        "Quantum mechanics describes the behavior of matter and energy at the atomic scale. Unlike classical physics quantum systems exhibit wave-particle duality and probabilistic behavior. Particles can exist in multiple states simultaneously through a phenomenon called quantum superposition. Measurement of a quantum system causes it to collapse into a single definite state. This property has profound implications for cryptography computing and our understanding of reality. Quantum computers leverage these principles to solve certain problems exponentially faster than classical computers.",
        "The Great Depression was a severe worldwide economic downturn that began in 1929. The stock market crash of October 1929 triggered a cascade of bank failures and business closures. Unemployment in the United States reached approximately 25 percent at the height of the crisis. President Franklin Roosevelt introduced the New Deal programs to provide relief and recovery. These programs created jobs through public works projects and established social safety nets. The depression finally ended with the economic mobilization for World War Two in the early 1940s.",
        "DNA replication is the biological process of producing two identical copies from one original molecule. The double helix structure is unwound by the enzyme helicase breaking the hydrogen bonds between base pairs. DNA polymerase then adds complementary nucleotides to each separated strand following base pairing rules. Adenine pairs with thymine while guanine pairs with cytosine in the new strands. The process is semiconservative meaning each new DNA molecule contains one original strand and one newly synthesized strand. Errors during replication are corrected by proofreading mechanisms built into the polymerase enzyme.",
        "The Renaissance was a cultural movement spanning the fourteenth to seventeenth centuries in Europe. It began in Italy and gradually spread across the entire European continent over several centuries. The movement was characterized by a revival of interest in classical Greek and Roman learning. Artists like Leonardo da Vinci and Michelangelo created masterpieces that redefined Western art forever. The invention of the printing press by Johannes Gutenberg accelerated the spread of Renaissance ideas immensely. This period laid the intellectual foundations for the modern scientific revolution and the Enlightenment.",
        "Neural networks are computational models inspired by the structure of biological brains in animals. They consist of interconnected layers of artificial neurons that process information in parallel. Each neuron receives input signals and applies a mathematical function to produce an output value. The network learns by adjusting the weights of connections between neurons based on training data. Deep neural networks with many hidden layers can learn highly complex patterns and representations. These models power modern artificial intelligence applications from image recognition to natural language processing.",
    ],
    "essay": [
        "Social media has fundamentally changed how people communicate with each other today globally. Many young people use platforms like Instagram and TikTok for several hours every single day. These apps allow users to share photos videos and messages with their friends almost instantly. Social media can help people maintain connections across extremely long distances worldwide. However these platforms also raise serious concerns about mental health and privacy protection. Many users report feeling anxious or depressed after comparing themselves to others online constantly. Cyberbullying has emerged as another significant problem on these popular social media sites.",
        "Climate change represents one of the most urgent challenges facing humanity in the twenty-first century. Scientists have documented rising global temperatures over the past one hundred years conclusively. Greenhouse gas emissions from industrial activities are the primary driver of this dangerous trend. The consequences include melting polar ice caps rising sea levels and more extreme weather events globally. Governments around the world must take immediate action to reduce their carbon emissions as soon as possible. Renewable energy sources like solar and wind power offer promising alternatives to fossil fuels today.",
        "Technology has transformed education in ways that were unimaginable just a generation ago worldwide. Students now have access to vast amounts of information through the internet at any moment. Digital learning platforms provide interactive lessons personalized feedback and progress tracking automatically. Teachers can use these tools to create more engaging and effective classroom experiences for everyone. However critics argue that excessive screen time may harm the social development of students in the long term. The best approach likely combines technology with traditional face-to-face teaching methods effectively.",
        "The importance of physical exercise for maintaining good health cannot be overstated by medical professionals. Regular physical activity strengthens the heart improves circulation and boosts the entire immune system naturally. Exercise also releases endorphins which are chemicals in the brain that improve mood and reduce stress. Studies show that people who exercise regularly live longer and have lower rates of chronic diseases overall. Despite these well-documented benefits many adults fail to meet the recommended weekly activity guidelines currently. Incorporating even small amounts of movement into daily routines can make a significant difference over time.",
        "Reading books offers numerous cognitive and emotional benefits beyond simple entertainment or passing time. Regular reading improves vocabulary enhances concentration and strengthens critical thinking skills in measurable ways. Fiction especially helps readers develop empathy by allowing them to experience different perspectives and lives virtually. In our increasingly digital world dominated by short-form content reading longer texts is more valuable than ever before. Libraries and schools must continue promoting reading as a fundamental skill for academic and personal success today.",
        "Artificial intelligence is rapidly transforming industries from healthcare to transportation in unprecedented ways fundamentally. Machine learning algorithms can now diagnose diseases from medical images with accuracy matching human doctors in many cases. These systems analyze vast amounts of data to identify patterns that humans might miss or overlook completely. However the widespread adoption of AI also raises important ethical questions about privacy and employment security going forward. Policymakers must develop regulations that encourage innovation while protecting citizens from potential harm caused by AI systems.",
        "Immigration has been a defining feature of human societies throughout recorded history without exception worldwide. People move across borders seeking better economic opportunities safety from persecution or family reunification primarily. Immigrants often bring valuable skills entrepreneurial energy and cultural diversity to their new home countries increasingly. However immigration can also create social tensions and strain public resources in receiving communities at various times. Balanced immigration policies that address both humanitarian concerns and practical economic needs are essential for the future globally.",
        "Space exploration has captured human imagination since the earliest civilizations looked up at the stars above them. The Apollo moon landing in 1969 represented one of the greatest technological achievements of humanity in all of history. More recently private companies like SpaceX have dramatically reduced the cost of launching payloads into orbit around Earth. Robotic missions have explored Mars Jupiter and even the outer reaches of our entire solar system comprehensively. The search for life beyond Earth remains one of the most profound scientific questions of our time and generation.",
        "The fashion industry has a significant environmental impact that many consumers do not fully realize or consider carefully. Fast fashion produces enormous amounts of textile waste and consumes vast quantities of water and chemicals annually worldwide. The production of cotton for clothing requires intensive pesticide use and irrigation in many developing countries increasingly. Consumers can reduce their environmental footprint by buying fewer higher-quality items and choosing sustainable brands whenever possible today. Governments should also implement stricter regulations on textile waste and chemical disposal from manufacturing facilities going forward.",
        "Online learning has become increasingly popular especially after the global pandemic forced schools to close their physical doors temporarily everywhere. Virtual classrooms offer flexibility and accessibility for students who might otherwise struggle to attend traditional in-person classes regularly now. However the lack of face-to-face interaction can lead to feelings of isolation and reduced motivation among some groups of learners unfortunately. Educational institutions must find ways to combine the convenience of online platforms with the social benefits of in-person instruction effectively for everyone.",
    ],
}
