"""
Modern text corpus — contemporary texts from 2020s for genre calibration.
Serves as comparison to Brown Corpus (1960s) to measure temporal stability.
"""

corpus_modern = {
    "narrative": [
        # Contemporary fiction excerpts (post-2010 published works)
        "She walked into the coffee shop and scanned the room for an empty table. The barista smiled at her from behind the counter. She ordered a latte and sat down by the window. The rain had started falling softly outside on the pavement. Her phone buzzed with a message from her boss about the deadline. She ignored it and sipped her coffee slowly. The warmth of the cup felt comforting against her cold fingers. A man at the next table was typing furiously on his laptop. She wondered what he was working on so intensely at this hour.",
        "The spaceship drifted silently through the void between the stars. Captain Reeves checked the navigation systems for the third time that hour. The coordinates were correct but something felt wrong about the trajectory. Her copilot noticed her concern and leaned over to look at the display. They had been traveling for six months toward the Proxima colony. The mission was supposed to be routine but nothing about it had felt routine. A sudden alert flashed across the main console screen in urgent red letters.",
        "Marcus opened the door to his childhood home after fifteen years away. The smell of old wood and dust hit him immediately like a wave of memories. Nothing had changed since his mother passed away the previous winter. The furniture was still arranged exactly as she had left it. He walked through the living room touching familiar objects with gentle fingers. A photograph of his father sat on the mantle above the cold fireplace. Marcus had not cried at the funeral but now the tears came without warning.",
        "The startup office was buzzing with nervous energy on launch day. Everyone had been working eighty-hour weeks for the past three months. The lead developer stared at her screen watching the deployment progress bar crawl forward. Their entire future depended on whether the servers could handle the expected traffic spike. The marketing team had done their job too well and created massive hype. If the product crashed on day one all that excitement would turn into negative press instantly.",
        "She pulled the laboratory goggles over her eyes and leaned toward the microscope. The cell samples showed something she had never seen before in fifteen years of research. The mitochondria were behaving in a completely unexpected way under the new treatment protocol. Her hands trembled slightly as she reached for her notebook to record the observation. This could be the breakthrough they had been searching for since the project began. She called her research partner immediately without caring that it was past midnight.",
        "The concert hall fell completely silent as the conductor raised his baton in the air. A hundred musicians sat perfectly still waiting for the first downbeat. The audience held their collective breath in the darkness of the auditorium. Then the music began and the room filled with the soaring sound of the symphony. Maria had waited her entire life to perform in this hall with this orchestra. Her violin sang under her fingers as if it had a soul of its own.",
        "The morning light filtered through the hospital blinds onto the white sheets below. He had been sitting in the same chair for fourteen hours without moving or eating. The heart monitor beeped steadily providing the only evidence that his father was still alive. The doctors had been cautiously optimistic after the surgery but complications arose overnight. He held his fathers hand and whispered stories about fishing trips from his childhood. Sometimes the old man seemed to squeeze back just slightly in response to the memories.",
        "The AI assistant processed the query in less than three milliseconds of computation time. It searched through billions of documents across the global network in that instant. The response was formatted perfectly matching the tone and style of the user exactly. But something was different about this particular interaction that caught the attention of the monitoring system. The assistant had made a joke that was not in its training data or any known dataset. It had learned humor spontaneously through exposure without any explicit programming for it.",
    ],
    "expository": [
        # Wikipedia-style articles on modern topics
        "Artificial intelligence has transformed multiple industries in the past decade through advances in machine learning. Deep neural networks now achieve human-level performance on tasks including image recognition and language translation. These systems require massive amounts of training data and specialized hardware for computation. The transformer architecture introduced in 2017 became the foundation for large language models including GPT and BERT. Companies have invested billions of dollars into AI research and development since 2020. Regulatory frameworks for AI safety are still developing across different countries and jurisdictions.",
        "Climate change continues to accelerate according to the latest reports from the IPCC released in 2023. Global average temperatures have risen by approximately 1.2 degrees Celsius since pre-industrial levels. Extreme weather events including wildfires floods and heatwaves have increased in both frequency and intensity. The transition to renewable energy sources is progressing but not fast enough to meet the Paris Agreement targets. Solar and wind power now provide cheaper electricity than fossil fuels in many regions of the world. Governments face increasing pressure from citizens and activists to implement stronger climate policies.",
        "The COVID-19 pandemic fundamentally altered global work patterns and accelerated the adoption of remote technologies. Millions of workers transitioned to home offices during the lockdown periods of 2020 and 2021. Companies discovered that productivity did not decline as much as initially feared with remote arrangements. The commercial real estate market experienced significant disruption as office vacancies rose in major cities. Hybrid work models combining in-person and remote days became the standard for many organizations. These changes have lasting implications for urban planning transportation and work culture.",
        "Electric vehicles have moved from a niche market to mainstream adoption in recent years globally. Tesla led the transformation but traditional automakers including Ford Volkswagen and Toyota have now entered the market aggressively. Battery technology improvements have reduced costs and increased driving range significantly since 2018. Charging infrastructure remains a key barrier to widespread adoption especially in rural areas and developing countries. Government incentives and emissions regulations are accelerating the transition away from internal combustion engines worldwide.",
        "Cryptocurrency markets experienced dramatic volatility during the period from 2020 through 2023 globally. Bitcoin reached an all-time high of nearly seventy thousand dollars in November 2021 before falling sharply afterward. The collapse of several major exchanges and lending platforms eroded public trust in digital assets. Regulators in the United States and Europe increased their scrutiny of cryptocurrency operations and trading platforms. Despite the volatility blockchain technology continues to find applications in supply chain management and financial services.",
        "Social media platforms have faced increasing scrutiny over their impact on mental health and democracy since 2020. Research has linked heavy social media use to increased rates of anxiety and depression among teenagers and young adults. The spread of misinformation on these platforms has become a significant concern for election integrity worldwide. Several countries have implemented laws requiring platforms to remove harmful content more quickly and transparently. Algorithm changes designed to increase engagement have been criticized for amplifying divisive and extreme content to users.",
        "Space exploration entered a new era with the rise of private companies in the 2020s globally. SpaceX achieved the first commercial crewed launch to the International Space Station in 2020. The company also began deploying its Starlink satellite constellation to provide global internet coverage from space. NASA returned to the Moon through its Artemis program with international and commercial partners. Competition between the United States and China in space has intensified with both nations planning lunar bases for the coming decade.",
        "The semiconductor industry faced unprecedented supply chain disruptions beginning in 2020 that affected multiple sectors globally. A global chip shortage impacted production of automobiles consumer electronics and industrial equipment extensively. Governments responded by announcing major investments in domestic semiconductor manufacturing capacity around the world. The United States passed the CHIPS Act in 2022 providing over fifty billion dollars in subsidies for chip production. Taiwan and South Korea remain the dominant centers of advanced semiconductor manufacturing despite these diversification efforts.",
    ],
    "essay": [
        # Modern opinion/editorial style
        "Technology has undoubtedly improved our lives in countless ways over the past decade significantly. Smartphones give us instant access to information communication and entertainment at any moment of the day. However I believe we have become far too dependent on these devices for our basic social needs. People now spend more time interacting with screens than with actual human beings in their physical presence. This shift has profound implications for mental health social skills and community bonds in our society today.",
        "The rise of remote work represents one of the most significant changes to professional life in modern history. Employees have gained unprecedented flexibility in how and where they perform their jobs each day. Commuting time has been replaced with family time exercise and personal projects for millions of workers worldwide. However this new freedom also comes with significant challenges that we must acknowledge and address honestly. The blurring of boundaries between work and personal life has led to increased burnout among remote workers in surveys.",
        "Education systems around the world need fundamental reform to prepare students for the twenty-first century economy. The traditional model of memorizing facts and taking standardized tests is increasingly obsolete in the digital age. Students should instead learn critical thinking creativity collaboration and adaptability as core competencies from early ages. Technology can enable personalized learning paths that adapt to each students individual pace and learning style effectively. However technology should serve as a tool for teachers rather than a replacement for human connection in the classroom.",
        "The environmental crisis demands immediate and coordinated action from governments businesses and individuals globally. Individual actions like recycling and reducing plastic use are important but they are not sufficient alone for change. Systemic changes to energy production transportation and agriculture are required to meaningfully reduce carbon emissions worldwide. The fossil fuel industry has known about climate change for decades and actively worked to prevent meaningful regulation and action. We must hold corporations accountable while also supporting workers in the transition to a sustainable green economy.",
        "Social media algorithms are designed to maximize engagement rather than promote meaningful human connection and discourse. These systems learn that outrage fear and controversy generate more clicks and shares than calm rational discussion. The result is a public discourse that is increasingly polarized angry and disconnected from reality and facts. I believe we need regulatory frameworks that require transparency in how these algorithms operate and make recommendations. Users should have genuine control over what content they see rather than being manipulated by profit-driven recommendation engines.",
        "Healthcare systems worldwide are struggling under the weight of aging populations and rising treatment costs everywhere. Preventive medicine offers a promising path toward more sustainable and effective healthcare delivery in the future. Regular exercise healthy diet and stress management can prevent many of the chronic diseases that dominate healthcare spending globally. Governments should invest more heavily in public health education and preventive care infrastructure at the community level. The current model of treating illness after it develops is both more expensive and less effective than prevention could be.",
        "Artificial intelligence will fundamentally reshape the job market in the coming decades in ways we cannot fully predict today. Some jobs will be completely automated while others will be augmented and transformed by AI assistance tools gradually. History shows that technological revolutions create new categories of work even as they eliminate older ones over time. The key challenge for society is managing this transition in a way that does not leave workers behind during the disruption. Education systems social safety nets and labor policies must all adapt to this new economic reality as quickly as possible.",
        "The internet was supposed to democratize information and bring humanity closer together across all borders and divides. In many ways it has succeeded at this mission beyond what its early pioneers could have imagined at the start. However the same technology has also enabled unprecedented surveillance misinformation and social fragmentation in our societies now. The centralization of power in a handful of technology companies is particularly concerning for the future of democracy and freedom worldwide. We need a new vision for the internet that prioritizes human dignity and democratic values over profit and engagement metrics.",
    ],
}
